[server]
  debug_trace = false

[bluemix]
  iam_url = "https://iam.stage1.bluemix.net"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = ""
  containers_api_route_private = "https://containers.test.cloud.ibm.com"
  containers_api_csrf_token = ""

[vpc]
  vpc_enabled = true
  g2_token_exchange_endpoint_url = "https://iam.stage1.bluemix.net"
  g2_riaas_endpoint_url = "https://us-south-stage01.iaasdev.cloud.ibm.com/"
  g2_riaas_endpoint_private_url = "https://us-south-stage01.iaasdev.cloud.ibm.com"
  g2_resource_group_id = ""
  g2_api_key = ""
  provider_type = "g2"
  vpc_block_provider_name = "vpc"
  encryption = false
  iks_token_exchange_endpoint_private_url = "https://containers.test.cloud.ibm.com"
  containers_api_csrf_token = ""
  max_retry_attempt  = 2 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  120 # 2 minutes
  api_version = "2020-06-16"   #"2019-07-02"
  vpc_api_generation = 2
  vpc_api_timeout = "120s"

[IKS]
  iks_enabled = true
  iks_block_provider_name = "iks-vpc-classic"
